branch-defaults:
  master:
    environment: creativeiInquiry-env-dev
deploy:
 artifact: target/creativei_lms-1.0-SNAPSHOT.jar
environment-defaults:
  creativeiInquiry-env-dev:
    branch: master
    repository: origin
global:
  application_name: creativei-inquiry
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/Java 8 running on
    64bit Amazon Linux/2.6.8
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
  
