server:
  port: 5000

##aws dev db creds
#spring:
#  datasource:
#    url: jdbc:mysql://creativeiinquiryinstance.c4ysnaxuqvet.ap-south-1.rds.amazonaws.com/creativei_inquiry
#    username=dbroot
#    password=db#creativei
#    testWhileIdle = true
#    validationQuery = SELECT 1
## Keep the connection alive if idle for a long time (needed in production)
#  # Show or not log for each sql query
#  jpa:
#    show-sql: true